# These are supported funding model platforms

github: heychrisd
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
librepay: chrisdiaz
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: paypal.me/ChrisDiaz
